#!/usr/bin/env python3
"""
android-module-symvers-generator (extract_symvers.py)
Author: isus203/xz529

Reconstruction of the Module.symvers file from already compiled .ko files, used when the original Module.symvers (generated by the kernel build system during make modules and normally NOT included in the device firmware) is unavailable.
# ===========================================================================
HOW IT WORKS
Every .ko file built with CONFIG_MODVERSIONS=y contains:
__versions — an array of struct modversion_info { unsigned long crc; char name[56]; } (64 bytes per entry on 64-bit architectures, where only the lower 4 bytes of the CRC are significant) for EVERY symbol imported by the module.
__ksymtab / __ksymtab_gpl — symbol tables that the module ITSELF exports (EXPORT_SYMBOL / EXPORT_SYMBOL_GPL respectively — these are two distinct sections, allowing precise identification of the export type).
__kcrctab / __kcrctab_gpl — parallel CRC arrays for these exports, stored in the EXACT same order as the corresponding __ksymtab(_gpl).
The script uses ONLY readelf and nm (no objcopy/objdump, as they fail on ARM64 in cross-compilation environments without multi-target binutils).
# ===========================================================================
WHAT'S NEW IN THIS VERSION
 1. Automatic EXPORT_SYMBOL_GPL detection: the symbol __ksymtab_<name> is looked up in the symbol table (readelf -Ws), and its section index (Ndx) is compared with the __ksymtab_gpl section index — if they match, it is a GPL export.
 2. Sanity-check: entries with crc==0 and names containing non-printable characters or invalid C identifiers are skipped.
 3. Statistics at the end: files processed, unique symbols, conflicts, and symbols without a local exporter (i.e., resolved to vmlinux).
 4. --verbose: warnings in stderr upon symbol name version conflicts between different modules (i.e., the same name having a different CRC).
 5. Arch-check: reads e_machine/class (32/64-bit) from the ELF header of each file, aborting immediately if architecture mismatches are detected during a single run (a common cause of "unexplained" CRC mismatches).
# ===========================================================================
USAGE
python3 extract_symvers.py mod1.ko mod2.ko ... > Module.symvers
python3 extract_symvers.py --scan /path/to/firmware_root > Module.symvers
python3 extract_symvers.py --scan DIR --verbose > Module.symvers
# ===========================================================================
LIMITATIONS (Full Disclosure)
 * The symbol order in __ksymtab(_gpl) is matched against __kcrctab(_gpl) by ascending offset within the section (readelf -Ws, 'Value' column) — this is the same principle the kernel's modpost relies on. While theoretical misalignment is possible if the linker rearranges sections non-standardly, it has not been encountered in practice.
 * Symbols that are exported but not imported by any scanned .ko, and for which the exporting module fails to provide parseable __ksymtab/__kcrctab data, will not be included in the output.

"""
import subprocess
import struct
import re
import sys
import os
import argparse
from collections import defaultdict


# --------------------------------------------------------------------- #
# Low-level helpers (without objcopy/objdump)                          #
# --------------------------------------------------------------------- #

def get_section_hex(ko_path, section):
    """Raw bytes of an ELF section via readelf -x (architecture-independent)."""
    r = subprocess.run(['readelf', '-x', section, ko_path],
                        capture_output=True, text=True)
    if r.returncode != 0 or 'Hex dump' not in r.stdout:
        return b''
    data = bytearray()
    for line in r.stdout.splitlines():
        m = re.match(r'\s*0x[0-9a-f]+\s+((?:[0-9a-f]{2,8}\s+){1,4})', line)
        if not m:
            continue
        for word in m.group(1).split():
            for i in range(0, len(word), 2):
                data.append(int(word[i:i + 2], 16))
    return bytes(data)


def get_elf_header(ko_path):
    """Returns (machine_str, class_str) of type ('AArch64', 'ELF64')."""
    r = subprocess.run(['readelf', '-h', ko_path], capture_output=True, text=True)
    machine, cls = None, None
    for line in r.stdout.splitlines():
        line = line.strip()
        if line.startswith('Machine:'):
            machine = line.split(':', 1)[1].strip()
        elif line.startswith('Class:'):
            cls = line.split(':', 1)[1].strip()
    return machine, cls


def get_section_index(ko_path, section_name):
    """Section index ([Nr]) by its name, or None if there is no section."""
    r = subprocess.run(['readelf', '-WS', ko_path], capture_output=True, text=True)
    for line in r.stdout.splitlines():
        m = re.match(r'\s*\[\s*(\d+)\]\s+(\S+)\s', line)
        if m and m.group(2) == section_name:
            return int(m.group(1))
    return None


def get_symbols_with_ndx(ko_path):
    """
    A list (value, ndx, name) of symbols via `readelf -Ws`, EXCLUDING
special symbols of type SECTION (e.g., the symbol "__ksymtab_gpl" itself)
    Self-referencing as a section symbol is not a true export, but rather results in a false "symbol" named "gpl" after the prefix is stripped.
    (if not filtered by Type).
value — numeric offset (for characters in a section = offset within it).
ndx — numeric index of the section ('UND'/'ABS', etc., are skipped).
    """
    r = subprocess.run(['readelf', '-Ws', ko_path], capture_output=True, text=True)
    result = []
    for line in r.stdout.splitlines():
        parts = line.split()
        if len(parts) < 8:
            continue
        # Format: Num: Value Size Type Bind Vis Ndx Name
        if not re.match(r'^\d+:$', parts[0]):
            continue
        value_str, typ, ndx_str = parts[1], parts[3], parts[6]
        name = parts[-1]
        if typ == 'SECTION':
            continue
        if not re.match(r'^\d+$', ndx_str):
            continue
        try:
            value = int(value_str, 16)
            ndx = int(ndx_str)
        except ValueError:
            continue
        result.append((value, ndx, name))
    return result


def parse_versions(data):
    """__versions: struct modversion_info { unsigned long crc(8б); char name[56]; }."""
    entries = []
    for off in range(0, len(data) - 63, 64):
        chunk = data[off:off + 64]
        crc = struct.unpack('<I', chunk[0:4])[0]
        name = chunk[8:].split(b'\x00')[0].decode('utf-8', 'replace')
        if name:
            entries.append((crc, name))
    return entries


def parse_kcrctab(raw):
    """__kcrctab(_gpl): u32 CRC array (order matches __ksymtab(_gpl))."""
    n = len(raw) // 4
    return list(struct.unpack(f'<{n}I', raw[:n * 4]))


IDENT_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')


def is_sane_symbol(crc, name):
    """Sanity-check: filter out CRC==0 and names that do not resemble the C-identifier."""
    if crc == 0:
        return False
    if not name or not IDENT_RE.match(name):
        return False
    return True


def get_own_exports(ko_path):
    """
    Returns a list (name, crc, is_gpl) of symbols that THIS module itself exports (EXPORT_SYMBOL/_GPL), with their real CRC, extracted
from their own __kcrctab/__kcrctab_gpl (matching in ascending order of the __ksymtab_<name> symbol offset within the corresponding
section).
    """
    exports = []
    ksymtab_idx = get_section_index(ko_path, '__ksymtab')
    ksymtab_gpl_idx = get_section_index(ko_path, '__ksymtab_gpl')

    all_syms = get_symbols_with_ndx(ko_path)

    for section_idx, kcrctab_section, is_gpl in (
        (ksymtab_idx, '__kcrctab', False),
        (ksymtab_gpl_idx, '__kcrctab_gpl', True),
    ):
        if section_idx is None:
            continue
        # __ksymtab_<name> symbols located in this section
        names_in_section = sorted(
            (value, name[len('__ksymtab_'):])
            for value, ndx, name in all_syms
            if ndx == section_idx and name.startswith('__ksymtab_')
        )
        crcs = parse_kcrctab(get_section_hex(ko_path, kcrctab_section))
        # Let's compare them in order - see the restrictions in the module docstring
        for (_value, name), crc in zip(names_in_section, crcs):
            exports.append((name, crc, is_gpl))

    return exports


def module_name_from_ko(path):
    base = os.path.basename(path)
    return base[:-3] if base.endswith('.ko') else base


def find_ko_files(root):
    result = []
    for dirpath, _dirs, files in os.walk(root):
        for f in files:
            if f.endswith('.ko'):
                result.append(os.path.join(dirpath, f))
    return sorted(result)


# --------------------------------------------------------------------- #
# Basic logic                                               #
# --------------------------------------------------------------------- #

def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('ko_files', nargs='*', help='Paths to .ko files')
    ap.add_argument('--scan', metavar='DIR',
                     help='Recursively find all .ko files in this directory')
    ap.add_argument('--verbose', action='store_true',
                     help='Print warnings about symbol version conflicts to stderr')
    args = ap.parse_args()

    ko_files = list(args.ko_files)
    if args.scan:
        ko_files.extend(find_ko_files(args.scan))
    if not ko_files:
        ap.print_help()
        sys.exit(1)

    # ---- Arch check ---------------------------------------------------
    arch_seen = None
    for ko in ko_files:
        machine, cls = get_elf_header(ko)
        if machine is None:
            continue
        key = (machine, cls)
        if arch_seen is None:
            arch_seen = key
        elif key != arch_seen:
            print(f"ERROR: architecture mismatch: '{ko}' is {machine}/{cls}, "
                  f"but previous files were {arch_seen[0]}/{arch_seen[1]}. "
                  f"Mixing architectures in one run will produce incorrect CRCs.",
                  file=sys.stderr)
            sys.exit(2)

    # ---- Collecting each module's own exports (with real CRC) ---
    # symbol_name -> list of (crc, is_gpl, modname)  (there may be several
    # modules "exporting" the same name - collision)
    exporters = defaultdict(list)
    # for modules whose __ksymtab/__kcrctab could not be matched by
    # length (rare case) - we use a simple list as a fallback
    # global names without CRC, so that at least the module name is known
    fallback_export_owner = {}

    files_scanned = 0
    for ko in ko_files:
        files_scanned += 1
        modname = module_name_from_ko(ko)
        own_exports = get_own_exports(ko)
        for name, crc, is_gpl in own_exports:
            if not is_sane_symbol(crc, name):
                continue
            exporters[name].append((crc, is_gpl, modname))
            fallback_export_owner.setdefault(name, modname)

    # ---- Checking for conflicts (different CRC for the same name in different modules) ----
    conflicts = 0
    for name, lst in exporters.items():
        distinct_crcs = {crc for crc, _gpl, _m in lst}
        if len(distinct_crcs) > 1:
            conflicts += 1
            if args.verbose:
                mods = ', '.join(f"'{m}'(0x{c:08x})" for c, _g, m in lst)
                print(f"Warning: Symbol '{name}' exported with disagreeing CRC by: {mods}",
                      file=sys.stderr)

    # ---- Collection of used symbols (to cover what couldn't be ----
# extracted directly from the exporter, for example, if the sections are in a strange order)
    per_module_used = {}
    for ko in ko_files:
        per_module_used[ko] = parse_versions(get_section_hex(ko, '__versions'))

    # ---- Forming the final rows of Module.symvers --------------------
    rows = []          # (crc, name, modname, export_type)
    seen_names = set()

    for name, lst in exporters.items():
        # In case of a conflict, we deterministically take the first entry (see --verbose
        # above for diagnostics), since Module.symvers can physically
        # contain only one line per symbol name
        crc, is_gpl, modname = lst[0]
        export_type = 'EXPORT_SYMBOL_GPL' if is_gpl else 'EXPORT_SYMBOL'
        rows.append((crc, name, modname, export_type))
        seen_names.add(name)

    used_but_unresolved = 0
    for ko, used in per_module_used.items():
        for crc, name in used:
            if name in seen_names:
                continue
            if not is_sane_symbol(crc, name):
                continue
            seen_names.add(name)
            exporter = fallback_export_owner.get(name, 'vmlinux')
            if exporter == 'vmlinux':
                used_but_unresolved += 1
            rows.append((crc, name, exporter, 'EXPORT_SYMBOL'))

    rows.sort(key=lambda r: r[1])

    # ---- Conclusion -----------------------------------------------------------
    print("# ======================================================================")
    print("# Module.symvers generated by android-module-symvers-generator")
    print("# Author: isus203/xz529")
    print("# ======================================================================")
    print("# Statistics:")
    print(f"# Files scanned: {files_scanned}")
    print(f"# Total symbols: {len(rows)}")
    print(f"# Conflicts found: {conflicts} ({'see stderr with --verbose' if not args.verbose else 'logged above'})")
    print(f"# Symbols resolved to vmlinux (no local exporter found): {used_but_unresolved}")
    print("# ======================================================================")

    for crc, name, modname, export_type in rows:
        print(f"0x{crc:08x}\t{name}\t{modname}\t{export_type}")

    print(f"# Done. {len(rows)} symbol(s) written.", file=sys.stderr)


if __name__ == '__main__':
    main()
