#!/usr/bin/env python3
"""
extract_symvers.py — Reconstruction of the Module.symvers file from already
compiled .ko files, used when the original Module.symvers (generated by 
the kernel build system during `make modules` and normally NOT included 
in the device firmware) is unavailable.

HOW IT WORKS
------------
Every .ko file built with CONFIG_MODVERSIONS=y contains a __versions 
section, which is an array of entries defined as follows:

    struct modversion_info {
        unsigned long crc;   // 8 bytes on 64-bit architectures (arm64/x86_64),
                             // though the actual CRC32 fits into the lower 4 bytes
        char name[56];       // null-padded symbol name
    };                       // total 64 bytes per entry

These are EXACTLY the same (crc, symbol) pairs that the kernel build 
system would write to Module.symvers for every symbol imported by 
the module. By collecting these entries from all .ko files in the 
firmware and matching each symbol to the module that actually exports 
it (using global symbols from its `nm` table), we can reconstruct a 
unified Module.symvers suitable for out-of-tree module compilation 
(`make M=... KBUILD_EXTRA_SYMBOLS=...` or substitution in 
KERNEL_SRC/Module.symvers).

LIMITATIONS (Honesty)
---------------------
- Does not distinguish between EXPORT_SYMBOL and EXPORT_SYMBOL_GPL 
  (all are written as EXPORT_SYMBOL) — this only affects license 
  compatibility checks during build, not the CRC matching itself.
- Symbols that are exported but NOT imported by any other .ko file 
  present in the dump will not be included — their CRCs cannot be 
  extracted without parsing the __kcrctab of the exporter module 
  directly (not implemented, rarely needed).
- Does not require objcopy/objdump (which often crash on ARM64 in 
  cross-environments lacking multi-target binutils) — all processing 
  is done via `readelf -x` (architecture-independent) and `nm`.

USAGE
-----
    # For specific files:
    python3 extract_symvers.py mod1.ko mod2.ko ... > Module.symvers

    # Recursively scan all .ko files in the firmware tree:
    python3 extract_symvers.py --scan /path/to/firmware_root > Module.symvers
"""
import subprocess
import struct
import re
import sys
import os
import argparse


def get_section_hex(ko_path, section):
    """Returns the raw bytes of an ELF section via readelf -x (without objcopy)."""
    r = subprocess.run(['readelf', '-x', section, ko_path],
                        capture_output=True, text=True)
    if r.returncode != 0 or 'Hex dump' not in r.stdout:
        return b''
    data = bytearray()
    for line in r.stdout.splitlines():
        m = re.match(r'\s*0x[0-9a-f]+\s+((?:[0-9a-f]{2,8}\s+){1,4})', line)
        if not m:
            continue
        for word in m.group(1).split():
            for i in range(0, len(word), 2):
                data.append(int(word[i:i + 2], 16))
    return bytes(data)


def parse_versions(data):
    """
    __versions: struct modversion_info { unsigned long crc; char name[56]; }
64 bytes/record on a 64-bit architecture (crc is 8 bytes, with only the lower 4 significant).
    """
    entries = []
    for off in range(0, len(data) - 63, 64):
        chunk = data[off:off + 64]
        crc = struct.unpack('<I', chunk[0:4])[0]
        name = chunk[8:].split(b'\x00')[0].decode('utf-8', 'replace')
        if name:
            entries.append((crc, name))
    return entries


def get_global_symbols(ko_path):
    """A list (addr, name) of global T/D/R/B symbols for the module (candidates for the module to export them via EXPORT_SYMBOL)."""
    r = subprocess.run(['nm', ko_path], capture_output=True, text=True)
    syms = []
    for line in r.stdout.splitlines():
        parts = line.split()
        if len(parts) == 3:
            addr, typ, name = parts
            if typ in ('T', 'D', 'R', 'B'):  # capital = global (not static)
                syms.append((int(addr, 16), name))
    return syms


def module_name_from_ko(path):
    base = os.path.basename(path)
    return base[:-3] if base.endswith('.ko') else base


def find_ko_files(root):
    result = []
    for dirpath, _dirs, files in os.walk(root):
        for f in files:
            if f.endswith('.ko'):
                result.append(os.path.join(dirpath, f))
    return sorted(result)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('ko_files', nargs='*', help='Paths to .ko files')
    ap.add_argument('--scan', metavar='DIR',
                     help='Recursively find all .ko files in this directory')
    args = ap.parse_args()

    ko_files = list(args.ko_files)
    if args.scan:
        ko_files.extend(find_ko_files(args.scan))
    if not ko_files:
        ap.print_help()
        sys.exit(1)

    exports_by_symbol = {}   # symbol_name -> module_name (the first exporter found)
    per_module_used = {}     # ko_path -> [(crc, name), ...]

    for ko in ko_files:
        modname = module_name_from_ko(ko)
        per_module_used[ko] = parse_versions(get_section_hex(ko, '__versions'))
        for _addr, name in get_global_symbols(ko):
            exports_by_symbol.setdefault(name, modname)

    print("#" + "="*70)
    print("# Module.symvers generated by android-module-symvers-generator")
    print("#")
    print("# Author: isus203/xz529")
    print("# Project: https://github.com/xz529/android-module-symvers-generator")
    print("#")
    print("# WARNING: This is a reconstructed file from __versions sections.")
    print("# Build artifact, does not distinguish EXPORT_SYMBOL vs EXPORT_SYMBOL_GPL.")
    print("# Valid for compiling out-of-tree modules on the target kernel.")
    print("#" + "="*70)
    print() # Empty line for indentation

    seen = set()
    count = 0
    for ko, used in per_module_used.items():
        for crc, name in used:
            key = (crc, name)
            if key in seen:
                continue
            seen.add(key)
            exporter = exports_by_symbol.get(name, 'vmlinux')
            print(f"0x{crc:08x}\t{name}\t{exporter}\tEXPORT_SYMBOL")
            count += 1

    print(f"# Total records: {count}", file=sys.stderr)


if __name__ == '__main__':
    main()
